var DashboardFactory_1 = require("./services/DashboardFactory");
var DashboardsService_1 = require("./services/DashboardsService");
var WidgetFactory_1 = require("./services/WidgetFactory");
var WidgetsService_1 = require("./services/WidgetsService");
var DashboardFactory_2 = require("./services/DashboardFactory");
exports.DashboardFactory = DashboardFactory_2.DashboardFactory;
var DashboardsService_2 = require("./services/DashboardsService");
exports.DashboardsService = DashboardsService_2.DashboardsService;
var WidgetFactory_2 = require("./services/WidgetFactory");
exports.WidgetFactory = WidgetFactory_2.WidgetFactory;
var WidgetsService_2 = require("./services/WidgetsService");
exports.WidgetsService = WidgetsService_2.WidgetsService;
var WidgetViewTypesService_1 = require('./services/WidgetViewTypesService');
exports.WidgetViewTypesService = WidgetViewTypesService_1.WidgetViewTypesService;
var widgets_1 = require("./widgets/widgets");
exports.WIDGET_PROVIDERS = widgets_1.WIDGET_PROVIDERS; // TODO: Remove this!
var views_1 = require("./views/views");
exports.WIDGET_VIEW_PROVIDERS = views_1.WIDGET_VIEW_PROVIDERS;
exports.DASHBOARD_PROVIDERS = [DashboardFactory_1.DashboardFactory, DashboardsService_1.DashboardsService, WidgetFactory_1.WidgetFactory, WidgetsService_1.WidgetsService];
//# sourceMappingURL=dashboard.js.map